### ISSUE TITLE
Issues with HAE-DAT csv file

### ISSUE THREAD

**Issue by Bresnane** [iobis/haedat-issues#18]
The beginning of the csv file of downloaded HAE-DAT data is OK. Once you reach the Microalgae section the data in the HAE-DAT record does not match the entry file on HAE-DAT. See entry for GB_99_008 vs HAE-DAT csv data below. When you dump all the data there seems to be some values e.g. 916 repeated. see other file below.

- [HAE-DAT GB99_008.xlsx](https://github.com/iobis/haedat-issues/files/1337696/HAE-DAT.GB99_008.xlsx)
- [GB data extract 27_09_17.xlsx](https://github.com/iobis/haedat-issues/files/1337697/GB.data.extract.27_09_17.xlsx)  
- [http://haedat.iode.org/viewEvent.php?eventID=1224](http://haedat.iode.org/viewEvent.php?eventID=1224)

field | value
-- | --
eventName | GB-99-008
eventYear | 1999
region | Shetland.
originalGridCode
monitoringProgramme | 1
programmeName | FRS Marine Laboratory Aberdeen Shellfish Hygiene monitoring programme
occurredBefore | 0
occurredBeforeText
waterDiscoloration | 0
highPhyto | 0
seafoodToxin | 1
massMortal | 0
foamMucil | 0
otherEffect | 0
otherEffectText
days | 0
months | 0
locationText | East Scotland.
latitude |  
longitude
additionalLocationInfo | The Shetland region of Scotland\' covers the offshore area and shoreline   enclosed by the coordinates 61 00.0 N/00 00.0 E, 61 00.0 N/02 00.0 W, 59 30.0   N/02 00.0 W and 59 30.0 N/ 00 00.0 E. 11 samples from 5 sites in this area   tested positive for DSP during this period. ICES Fishing Area: IV a.
eventDate
initialDate | 28/07/1999
finalDate | 27/09/1999
quarantineStartDate
quarantineEndDate
additionalDateInfo
causativeKnown | 1
pigmentAnalysisInfo
additionalAlgaeInfo
toxicityDetected | 1
toxicityRange | DSP positive
humansAffected | 0
fishAffected | 0
naturalFishAffected | 0
aquacultureFishAffected | 0
planktonicAffected | 0
benthicAffected | 0
shellfishAffected | 1
birdsAffected | 0
otherTerrestrialAffected | 0
aquaticMammalsAffected | 0
seaweedAffected | 0
effectsComments
unexplainedToxicity | 0
toxicityComments
transvectors
eventBiblio
syndromeText
active |  
created_at
updated_at | 15/04/2015
checked_at
countryName | UNITED KINGDOM
syndromeName | DSP
speciesContaining
additionalHarmfulEffectInfo
toxinAssayComments
assaytype
concentration
toxinType
toxin |  
causativeSpeciesName0 | Dinophysis acuminata
cellsPerLitre0 | 916
comments0 | 200
additionalSpeciesName0 | Dinophysis spp.
additionalCellsPerLitre0 | 962
additionalComments0 | 100
causativeSpeciesName1
cellsPerLitre1
comments1
causativeSpeciesName2
cellsPerLitre2
comments2
causativeSpeciesName3
cellsPerLitre3
comments3
additionalSpeciesName1
additionalCellsPerLitre1
additionalComments1
additionalSpeciesName2
additionalCellsPerLitre2
additionalComments2

**Comment by pieterprovoost** [comment]
Fix implemented, please check if it looks better now.

**Comment by Bresnane** [comment]
Thanks Pieter.

I've had a quick look and there are still a dodgy looking things there. I have raised them in a new issue - I wasn't sure if I should use the old one.

Eileen
